SELECT COMPANYNAME,BPNAME,SUM(ExtCost),SUM(Inventory_Fact.QUANTITY)
FROM Inventory_Fact 
    JOIN BRANCH_PLANT_DIM ON INVENTORY_FACT.BRANCHPLANTKEY = BRANCH_PLANT_DIM.BRANCHPLANTKEY
    JOIN COMPANY_DIM ON BRANCH_PLANT_DIM.COMPANYKEY = COMPANY_DIM.COMPANYKEY
WHERE INVENTORY_FACT.TRANSTYPEKEY = 2
GROUP BY ROLLUP( COMPANYNAME,BPNAME );