    SELECT CalMonth,CUST_VENDOR_DIM.ADDRCATCODE1,SUM(ExtCost),SUM(Quantity)
    FROM Inventory_Fact 
        JOIN CUST_VENDOR_DIM ON INVENTORY_FACT.CUSTVENDORKEY = CUST_VENDOR_DIM.CUSTVENDORKEY
        JOIN DATE_DIM ON INVENTORY_FACT.DateKey = Date_Dim.DateKey
    WHERE INVENTORY_FACT.TRANSTYPEKEY = 5 AND DATE_DIM.CalYear = 2011
    GROUP BY CalMonth,CUST_VENDOR_DIM.ADDRCATCODE1
UNION
    SELECT CalMonth,NULL,SUM(ExtCost),SUM(Quantity)
    FROM Inventory_Fact 
        JOIN CUST_VENDOR_DIM ON INVENTORY_FACT.CUSTVENDORKEY = CUST_VENDOR_DIM.CUSTVENDORKEY
        JOIN DATE_DIM ON INVENTORY_FACT.DateKey = Date_Dim.DateKey
    WHERE INVENTORY_FACT.TRANSTYPEKEY = 5 AND DATE_DIM.CalYear = 2011
    GROUP BY CalMonth
UNION
    SELECT NULL,CUST_VENDOR_DIM.ADDRCATCODE1,SUM(ExtCost),SUM(Quantity)
    FROM Inventory_Fact 
        JOIN CUST_VENDOR_DIM ON INVENTORY_FACT.CUSTVENDORKEY = CUST_VENDOR_DIM.CUSTVENDORKEY
        JOIN DATE_DIM ON INVENTORY_FACT.DateKey = Date_Dim.DateKey
    WHERE INVENTORY_FACT.TRANSTYPEKEY = 5 AND DATE_DIM.CalYear = 2011
    GROUP BY CUST_VENDOR_DIM.ADDRCATCODE1
UNION
    SELECT NULL,NULL,SUM(ExtCost),SUM(Quantity)
    FROM Inventory_Fact 
    JOIN CUST_VENDOR_DIM ON INVENTORY_FACT.CUSTVENDORKEY = CUST_VENDOR_DIM.CUSTVENDORKEY
    JOIN DATE_DIM ON INVENTORY_FACT.DateKey = Date_Dim.DateKey WHERE INVENTORY_FACT.TRANSTYPEKEY = 5 AND DATE_DIM.CalYear = 2011;