SELECT CalMonth,CUST_VENDOR_DIM.ADDRCATCODE1,
    SUM(ExtCost),SUM(Quantity),
    GROUPING_ID(CalMonth,CUST_VENDOR_DIM.ADDRCATCODE1) AS Group_Number
FROM Inventory_Fact 
    JOIN CUST_VENDOR_DIM ON INVENTORY_FACT.CUSTVENDORKEY = CUST_VENDOR_DIM.CUSTVENDORKEY
    JOIN DATE_DIM ON INVENTORY_FACT.DateKey = Date_Dim.DateKey
WHERE INVENTORY_FACT.TRANSTYPEKEY = 5
    AND DATE_DIM.CalYear = 2011
GROUP BY CUBE(CalMonth,CUST_VENDOR_DIM.ADDRCATCODE1);